title: Aklima K. Lima (Ph.D.)
logo: images/professional_photo.jpeg
description: |
  Email: aklima.phy.du@gmail.com  
  LinkedIn: linkedin.com/in/aklimakhanam
show_downloads: true
theme: jekyll-theme-minimal
