title: Aklima Khanam Lima
logo: images/professional_photo.jpeg
description: |
  Email: aklima.phy.du@gmail.com Â· aklima@syr.edu 
  LinkedIn: linkedin.com/in/aklimakhanam
show_downloads: true
theme: jekyll-theme-minimal
